import Head from 'next/head'
import { Text, View } from 'reshaped'

export default function Home() {
  return (
    <>
      <Head>
        <title>gyanash.ekka.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <View height={"100vh"} align='center' justify="center">
        <Text variant='title-1' color='primary'>Reshaped Initialized</Text>
      </View>
    </>
  )
}