import Head from 'next/head'
import { Hidden } from 'reshaped'
import FullScreen from 'src/components/screens/fullScreen'
import MiddleScreen from 'src/components/screens/middleScreen'
import MobileScreen from 'src/components/screens/mobileScreen'

export default function Home() {
  return (
    <>
      <Head>
        <title>gyanash.ekka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hidden hide={{ s: true, l: false }}>
        <FullScreen />
      </Hidden>
      <Hidden hide={{ s: true, m: false, l: true }}>
        <MiddleScreen />
      </Hidden>
      <Hidden hide={{ s: false, m: true }}>
        <MobileScreen />
      </Hidden>
    </>
  )
}